// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./cel-napi.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-android-arm64')
        const bindingPackageVersion = require('@dpagk/cellar-napi-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./cel-napi.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-android-arm-eabi')
        const bindingPackageVersion = require('@dpagk/cellar-napi-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./cel-napi.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-win32-x64-gnu')
        const bindingPackageVersion = require('@dpagk/cellar-napi-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./cel-napi.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-win32-x64-msvc')
        const bindingPackageVersion = require('@dpagk/cellar-napi-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./cel-napi.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-win32-ia32-msvc')
        const bindingPackageVersion = require('@dpagk/cellar-napi-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./cel-napi.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-win32-arm64-msvc')
        const bindingPackageVersion = require('@dpagk/cellar-napi-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./cel-napi.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@dpagk/cellar-napi-darwin-universal')
      const bindingPackageVersion = require('@dpagk/cellar-napi-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./cel-napi.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-darwin-x64')
        const bindingPackageVersion = require('@dpagk/cellar-napi-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./cel-napi.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-darwin-arm64')
        const bindingPackageVersion = require('@dpagk/cellar-napi-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./cel-napi.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-freebsd-x64')
        const bindingPackageVersion = require('@dpagk/cellar-napi-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./cel-napi.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-freebsd-arm64')
        const bindingPackageVersion = require('@dpagk/cellar-napi-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./cel-napi.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-x64-musl')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./cel-napi.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-x64-gnu')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./cel-napi.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-arm64-musl')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./cel-napi.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-arm64-gnu')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./cel-napi.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-arm-musleabihf')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./cel-napi.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./cel-napi.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-loong64-musl')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./cel-napi.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-loong64-gnu')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./cel-napi.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-riscv64-musl')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./cel-napi.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dpagk/cellar-napi-linux-riscv64-gnu')
          const bindingPackageVersion = require('@dpagk/cellar-napi-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./cel-napi.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-linux-ppc64-gnu')
        const bindingPackageVersion = require('@dpagk/cellar-napi-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./cel-napi.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-linux-s390x-gnu')
        const bindingPackageVersion = require('@dpagk/cellar-napi-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./cel-napi.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-openharmony-arm64')
        const bindingPackageVersion = require('@dpagk/cellar-napi-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./cel-napi.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-openharmony-x64')
        const bindingPackageVersion = require('@dpagk/cellar-napi-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./cel-napi.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dpagk/cellar-napi-openharmony-arm')
        const bindingPackageVersion = require('@dpagk/cellar-napi-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.1.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.1.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./cel-napi.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
    try {
      wasiBinding = require('@dpagk/cellar-napi-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.activateApp = nativeBinding.activateApp
module.exports.adapterExecuteAction = nativeBinding.adapterExecuteAction
module.exports.adapterGetElements = nativeBinding.adapterGetElements
module.exports.adapterInfo = nativeBinding.adapterInfo
module.exports.addKnowledge = nativeBinding.addKnowledge
module.exports.addObservation = nativeBinding.addObservation
module.exports.addScopedKnowledge = nativeBinding.addScopedKnowledge
module.exports.axElementAtPosition = nativeBinding.axElementAtPosition
module.exports.axGetAllWindows = nativeBinding.axGetAllWindows
module.exports.axGetMenuBar = nativeBinding.axGetMenuBar
module.exports.axIsSettable = nativeBinding.axIsSettable
module.exports.axPerformAction = nativeBinding.axPerformAction
module.exports.axPermissionGranted = nativeBinding.axPermissionGranted
module.exports.axRequestPermission = nativeBinding.axRequestPermission
module.exports.axSetValue = nativeBinding.axSetValue
module.exports.bindBrowserCdpUrl = nativeBinding.bindBrowserCdpUrl
module.exports.bootCortex = nativeBinding.bootCortex
module.exports.buildContextFromElements = nativeBinding.buildContextFromElements
module.exports.buildPlanPrompt = nativeBinding.buildPlanPrompt
module.exports.canonicalBuildPlanningView = nativeBinding.canonicalBuildPlanningView
module.exports.canonicalDecideNext = nativeBinding.canonicalDecideNext
module.exports.canonicalExecuteStep = nativeBinding.canonicalExecuteStep
module.exports.canonicalPerceive = nativeBinding.canonicalPerceive
module.exports.canonicalVerifyDone = nativeBinding.canonicalVerifyDone
module.exports.captureScreen = nativeBinding.captureScreen
module.exports.captureWindow = nativeBinding.captureWindow
module.exports.cdpDiscoverTargets = nativeBinding.cdpDiscoverTargets
module.exports.cdpEvaluate = nativeBinding.cdpEvaluate
module.exports.cdpGetCookies = nativeBinding.cdpGetCookies
module.exports.cdpGetLocalStorage = nativeBinding.cdpGetLocalStorage
module.exports.cdpGetNetworkRequests = nativeBinding.cdpGetNetworkRequests
module.exports.cdpGetPageContent = nativeBinding.cdpGetPageContent
module.exports.cdpIsSetup = nativeBinding.cdpIsSetup
module.exports.cdpNavigate = nativeBinding.cdpNavigate
module.exports.cdpSetupInstall = nativeBinding.cdpSetupInstall
module.exports.cdpSetupUninstall = nativeBinding.cdpSetupUninstall
module.exports.celVersion = nativeBinding.celVersion
module.exports.click = nativeBinding.click
module.exports.connectAdapter = nativeBinding.connectAdapter
module.exports.consumeCortexAnomalies = nativeBinding.consumeCortexAnomalies
module.exports.cortexLastTickAgeMs = nativeBinding.cortexLastTickAgeMs
module.exports.cortexRefreshNow = nativeBinding.cortexRefreshNow
module.exports.cortexStalledTicks = nativeBinding.cortexStalledTicks
module.exports.cortexTickCount = nativeBinding.cortexTickCount
module.exports.decomposeGoal = nativeBinding.decomposeGoal
module.exports.disconnectAdapter = nativeBinding.disconnectAdapter
module.exports.doubleClick = nativeBinding.doubleClick
module.exports.drag = nativeBinding.drag
module.exports.finishRun = nativeBinding.finishRun
module.exports.gestureDrain = nativeBinding.gestureDrain
module.exports.gestureStart = nativeBinding.gestureStart
module.exports.gestureStop = nativeBinding.gestureStop
module.exports.getContext = nativeBinding.getContext
module.exports.getContextFocused = nativeBinding.getContextFocused
module.exports.getObservations = nativeBinding.getObservations
module.exports.getQuickContext = nativeBinding.getQuickContext
module.exports.getRunHistory = nativeBinding.getRunHistory
module.exports.getStepResults = nativeBinding.getStepResults
module.exports.getWorkingMemory = nativeBinding.getWorkingMemory
module.exports.initTracing = nativeBinding.initTracing
module.exports.isCortexRunning = nativeBinding.isCortexRunning
module.exports.keyCombo = nativeBinding.keyCombo
module.exports.keyDown = nativeBinding.keyDown
module.exports.keyPress = nativeBinding.keyPress
module.exports.keyUp = nativeBinding.keyUp
module.exports.listCaptureWindows = nativeBinding.listCaptureWindows
module.exports.listMonitors = nativeBinding.listMonitors
module.exports.listWindows = nativeBinding.listWindows
module.exports.llmComplete = nativeBinding.llmComplete
module.exports.llmCompleteWithImage = nativeBinding.llmCompleteWithImage
module.exports.llmCompleteWithMessages = nativeBinding.llmCompleteWithMessages
module.exports.llmCompleteWithRole = nativeBinding.llmCompleteWithRole
module.exports.logStep = nativeBinding.logStep
module.exports.makeReference = nativeBinding.makeReference
module.exports.mouseMove = nativeBinding.mouseMove
module.exports.mouseMoveSmooth = nativeBinding.mouseMoveSmooth
module.exports.mousePosition = nativeBinding.mousePosition
module.exports.notifyCortexAction = nativeBinding.notifyCortexAction
module.exports.paste = nativeBinding.paste
module.exports.planStep = nativeBinding.planStep
module.exports.planStepBlind = nativeBinding.planStepBlind
module.exports.pollEvents = nativeBinding.pollEvents
module.exports.probeAdapter = nativeBinding.probeAdapter
module.exports.queryKnowledge = nativeBinding.queryKnowledge
module.exports.readCortexModel = nativeBinding.readCortexModel
module.exports.registerAdapter = nativeBinding.registerAdapter
module.exports.reportCortexActionFailure = nativeBinding.reportCortexActionFailure
module.exports.reportCortexActionSuccess = nativeBinding.reportCortexActionSuccess
module.exports.resolveReference = nativeBinding.resolveReference
module.exports.rightClick = nativeBinding.rightClick
module.exports.runEviction = nativeBinding.runEviction
module.exports.runGoalRust = nativeBinding.runGoalRust
module.exports.scroll = nativeBinding.scroll
module.exports.searchKnowledge = nativeBinding.searchKnowledge
module.exports.selectAll = nativeBinding.selectAll
module.exports.shellExec = nativeBinding.shellExec
module.exports.startRun = nativeBinding.startRun
module.exports.startWatchdog = nativeBinding.startWatchdog
module.exports.stopCortex = nativeBinding.stopCortex
module.exports.stopWatchdog = nativeBinding.stopWatchdog
module.exports.tripleClick = nativeBinding.tripleClick
module.exports.typeText = nativeBinding.typeText
module.exports.updateWorkingMemory = nativeBinding.updateWorkingMemory
