/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Activate (bring to front) a macOS application by name.
 * Uses `open -a "AppName"` which is the most reliable app switching method.
 * If the app is already running, it activates; if not, it launches.
 * Activate (bring to front) an application by name.
 * For browsers: prefers activating CEL's dedicated CDP browser instance when
 * one already exists. It never quits or relaunches the user's browser.
 */
export declare function activateApp(appName: string): boolean

/** Execute a named action on a registered adapter (JSON in/out). */
export declare function adapterExecuteAction(name: string, action: string, params: string): Promise<string>

/** Get context elements from a registered adapter (JSON-serialized). */
export declare function adapterGetElements(name: string): Promise<string>

/** Get adapter info (JSON-serialized). */
export declare function adapterInfo(name: string): Promise<string>

/** Add a knowledge fact. Returns the row ID. */
export declare function addKnowledge(dbPath: string, content: string, source: string): number

/** Add an observation. Returns the observation ID. */
export declare function addObservation(dbPath: string, workflowName: string, content: string, priority: string, sourceRunIds: Array<number>): number

/** Add a scoped knowledge fact. Returns the row ID. */
export declare function addScopedKnowledge(dbPath: string, content: string, source: string, workflowScope?: string | undefined | null, tags?: string | undefined | null): number

/**
 * Get the accessibility element at a screen coordinate (hit testing).
 * Returns JSON AccessibilityElement, or "null" if nothing found.
 */
export declare function axElementAtPosition(x: number, y: number): string

/**
 * Get ALL windows of the focused application (not just the focused one).
 * Returns JSON array of AccessibilityElement (shallow trees — title/bounds per window).
 */
export declare function axGetAllWindows(): string

/**
 * Get the menu bar structure of the focused application.
 * Returns JSON array of MenuBarItem: [{ path, label, shortcut, enabled }, ...]
 * This is the AI's "command palette" — all discoverable app commands.
 */
export declare function axGetMenuBar(): string

/** Check if an element's value can be set directly via the accessibility API. */
export declare function axIsSettable(elementId: string): boolean

/**
 * Execute an action on an accessibility element directly via the native API.
 * More reliable than mouse/keyboard injection for buttons, checkboxes, menu items.
 * `action`: "click", "activate", "increment", "decrement", "cancel", "show_menu",
 *           "scroll_to_visible", "raise", "pick", "delete".
 */
export declare function axPerformAction(elementId: string, action: string): boolean

/**
 * Check whether the current host process has been granted macOS Accessibility
 * permission. Returns true when granted, false when denied. On non-macOS
 * platforms returns true (no-op — Accessibility permission is a macOS concept).
 *
 * Pure boolean check via `AXIsProcessTrusted()` — does not prompt the user.
 * Cheap (microseconds) so safe to call on every MCP tool invocation as a
 * pre-flight guard rather than failing late inside an AX traversal.
 */
export declare function axPermissionGranted(): boolean

/**
 * Trigger the macOS Accessibility permission prompt for the host process.
 *
 * Returns the trust state. Side effect: shows the system notification for
 * processes not yet in the Privacy & Security list. Clicking the notification
 * opens System Settings with the host process pre-selected, so the user only
 * has to flip the toggle.
 *
 * macOS does not pick up permission changes mid-process — the host process
 * (Cursor, Claude Code, Terminal.app, etc.) must be restarted after the user
 * grants permission for it to take effect.
 *
 * Safe to call on every denied tool invocation; macOS itself rate-limits the
 * notification UI so we don't spam the user.
 */
export declare function axRequestPermission(): boolean

/**
 * Set a value directly on an accessibility element (bypasses mouse/keyboard entirely).
 * For text fields: sets the text content. For checkboxes: "true"/"false".
 * For sliders: numeric string. Most reliable form-filling path.
 */
export declare function axSetValue(elementId: string, value: string): boolean

/**
 * Phase 3 of ADR-unify-browser-ownership: tell the running cortex which CDP
 * URL its BrowserAdapter should attach to.
 *
 * Used after `cel.ensureBrowser()` spawns a Chromium with
 * `--remote-debugging-port=PORT` — TS calls this so the Rust cortex doesn't
 * have to discover the browser via `cel_cdp::connect_to_focused_app`, which
 * silently fails for headless browsers (no macOS-frontmost match).
 *
 * Silently no-ops when Cortex isn't running. This lets `cel.ensureBrowser`
 * call this unconditionally — the Phase 2 path (BrowserAdapter without
 * cortex) just doesn't have anything to bind to, which is fine.
 *
 * Errors only if Cortex IS running and the CDP URL is unreachable.
 */
export declare function bindBrowserCdpUrl(url: string): Promise<void>

/** Boot the Rust Cortex — starts the always-on 200ms perception tick loop. */
export declare function bootCortex(): void

/**
 * Build a ScreenContext from externally-provided elements (e.g., browser CDP data).
 *
 * Routes through the Rust pipeline for unified confidence scoring, element type
 * normalization, noise filtering, action assignment, and sorting.
 *
 * This is the browser adapter's entry point into the Rust CEL core.
 * Elements should have `element_type` set to the raw ARIA role string —
 * the pipeline normalizes it to CEL types via `aria_role_to_cel_type()`.
 *
 * Parameters:
 * - elements_json: JSON array of ContextElement (raw ARIA roles as element_type)
 * - network_events_json: JSON array of HttpEvent (CDP-level HTTP requests)
 * - app_name: Application name (e.g., "Browser")
 * - window_title: Window/page title
 *
 * Returns: JSON string of ScreenContext with scored/normalized elements.
 */
export declare function buildContextFromElements(elementsJson: string, networkEventsJson: string, appName: string, windowTitle: string): string

/**
 * Build the system + user prompts for planning WITHOUT calling the LLM.
 * Returns JSON: { "system": "...", "user": "..." }
 *
 * Use this to get the exact prompts that `plan_step` would use, then call
 * `llm_complete_with_image` separately with a screenshot attached.
 */
export declare function buildPlanPrompt(goal: string, contextJson: string, historyJson: string, maxSteps?: number | undefined | null, loopWarning?: string | undefined | null, provider?: string | undefined | null, model?: string | undefined | null): string

/**
 * Build a budgeted `PlanningView` from current cortex state (or from
 * caller-provided perception + caps for stateless mode).
 *
 * **Stateful** (default): `perception_json` and `caps_json` are `None`.
 * Uses the booted cortex via [`canonical_perceive`] to read fresh
 * perception + caps, then builds the view. Errors if the cortex isn't
 * running.
 *
 * **Stateless**: `perception_json` and `caps_json` are both provided.
 * Builds the view from the caller's perception/caps. Useful for the eval
 * harness, replay tooling, and any caller that already has a perception
 * snapshot.
 * Optional `adapter_facts_json`, `cortex_anomalies_json`, and
 * `cortex_freshness_json` can accompany a stateless frame; when omitted
 * and a cortex is booted, the stateful signals are read live.
 *
 * `budget_json` is an optional serialized [`PlanningBudget`]. When
 * omitted, defaults are used (see `PlanningBudget::default`).
 */
export declare function canonicalBuildPlanningView(goal: string, budgetJson?: string | undefined | null, perceptionJson?: string | undefined | null, capsJson?: string | undefined | null, adapterFactsJson?: string | undefined | null, cortexAnomaliesJson?: string | undefined | null, cortexFreshnessJson?: string | undefined | null): Promise<string>

/**
 * Run the LLM planner's `decide_next` against a `PlanningView`.
 *
 * Pure planner call — no cortex dependency. Caller is expected to have
 * built the view via [`canonical_build_planning_view`] (or any other
 * source that produces a valid `PlanningView` JSON).
 *
 * **Signature changed in PR1b**: previously took `perception_json` +
 * `caps_json`. Now takes `view_json`. The cortex/planner separation
 * at the Rust contract is mirrored on the JS surface.
 */
export declare function canonicalDecideNext(viewJson: string, historyJson: string, sharedMemoryJson: string, screenshotBase64?: string | undefined | null): Promise<string>

export declare function canonicalExecuteStep(stepJson: string): Promise<string>

export declare function canonicalPerceive(captureScreenshot?: boolean | undefined | null): Promise<string>

/**
 * Run the LLM planner's `verify_done` against a `PlanningView`.
 *
 * **Signature changed in PR1b**: previously took `perception_json`. Now
 * takes `view_json`. Caller builds the view via
 * [`canonical_build_planning_view`].
 */
export declare function canonicalVerifyDone(viewJson: string, summary: string, sharedMemoryJson: string, screenshotBase64?: string | undefined | null): Promise<string>

/**
 * Capture a screenshot and return as PNG bytes.
 *
 * `display_id`:
 *   - Some(n): capture exactly that monitor.
 *   - None: capture the monitor containing the frontmost app's key window
 *     (resolved via cel-signals). Falls back to the primary monitor when no
 *     frontmost window can be located. Behaviour-preserving for callers who
 *     don't pass the parameter on a single-display setup, but correctly
 *     captures the active display on multi-monitor rigs where the frontmost
 *     app is on a secondary display.
 */
export declare function captureScreen(displayId?: number | undefined | null): Buffer

/** Capture a window by platform capture ID and return as PNG bytes. */
export declare function captureWindow(windowId: number): Buffer

/** Discover available CDP targets. Returns JSON array of CdpTarget. */
export declare function cdpDiscoverTargets(): string

/**
 * Execute JavaScript in the focused browser tab via CDP Runtime.evaluate.
 * Returns the JSON-serialized result value, or "null" if no value.
 */
export declare function cdpEvaluate(expression: string): Promise<string>

/** Get all cookies from the focused CDP target. Returns JSON array. */
export declare function cdpGetCookies(): Promise<string>

/** Get a localStorage value by key from the focused CDP target. */
export declare function cdpGetLocalStorage(key: string): Promise<string>

/**
 * Get recent network requests (real HTTP data) from the focused CDP target.
 * Returns JSON array of HttpEvent.
 */
export declare function cdpGetNetworkRequests(limit?: number | undefined | null): Promise<string>

/**
 * Extract page content from the first available CDP target.
 * Returns JSON PageContent, or "null" if no CDP target is available.
 */
export declare function cdpGetPageContent(): Promise<string>

/** Check if the CDP LaunchAgent is installed. */
export declare function cdpIsSetup(): boolean

/** Navigate the focused CDP target to a URL. */
export declare function cdpNavigate(url: string): Promise<void>

/**
 * Install the LaunchAgent that enables CDP on all Electron apps.
 * Returns "installed" if newly installed, "already_installed" if already present.
 */
export declare function cdpSetupInstall(): string

/**
 * Uninstall the CDP LaunchAgent.
 * Returns "uninstalled" or "not_installed".
 */
export declare function cdpSetupUninstall(): string

/** Get the CEL runtime version. */
export declare function celVersion(): string

/** Left-click at absolute screen coordinates. */
export declare function click(x: number, y: number): void

/** Connect a registered adapter to its target application. */
export declare function connectAdapter(name: string): Promise<void>

/** Consume anomalies from the Cortex's anomaly queue. Returns JSON array. */
export declare function consumeCortexAnomalies(): string

/**
 * Milliseconds since the last successful tick. `None` if no tick has fired
 * (cortex not booted, or boot is in progress). A steadily-growing number
 * means the tick loop is stalled.
 */
export declare function cortexLastTickAgeMs(): number | null

/**
 * Force an out-of-band tick and return when it completes. Returns the
 * tick_count after the triggered tick. Times out after `timeout_ms`
 * (default 500); on timeout, `stalled_ticks` increments and this returns
 * an Err.
 */
export declare function cortexRefreshNow(timeoutMs?: number | undefined | null): Promise<number>

/** Count of `refresh_now` calls that timed out waiting for a tick. */
export declare function cortexStalledTicks(): number

/** Total successful ticks since boot. 0 if Cortex not running. */
export declare function cortexTickCount(): number

/**
 * Decompose a complex goal into advisory milestones.
 * Returns a JSON string with feasibility assessment and milestone list.
 */
export declare function decomposeGoal(goal: string, contextJson: string, totalStepBudget: number, historyAdvice?: string | undefined | null): Promise<string>

/** Disconnect a registered adapter. */
export declare function disconnectAdapter(name: string): Promise<void>

/** Double-click at absolute screen coordinates. */
export declare function doubleClick(x: number, y: number): void

/** Drag from one point to another (left mouse button). */
export declare function drag(fromX: number, fromY: number, toX: number, toY: number): void

/** Finish a workflow run. */
export declare function finishRun(dbPath: string, runId: number, status: string): void

/**
 * Drain all accumulated gesture events since last call.
 * Returns JSON array of GestureEvent.
 */
export declare function gestureDrain(): string

/**
 * Start capturing trackpad gestures (pinch, swipe, rotate, smart zoom).
 * Events accumulate in a buffer — call gesture_drain() to retrieve them.
 * Requires accessibility permissions on macOS.
 */
export declare function gestureStart(): void

/** Stop capturing trackpad gestures. */
export declare function gestureStop(): void

/**
 * Get the unified screen context — merges all available streams.
 * Returns JSON string of ScreenContext.
 */
export declare function getContext(): string

/**
 * Get focused context for a single element by ID.
 * Returns JSON FocusedContext, or "null" if not found.
 */
export declare function getContextFocused(elementId: string): string

/** Get active observations for a workflow. Returns JSON string. */
export declare function getObservations(dbPath: string, workflowName: string, limit: number): string

/**
 * Get minimal context: frontmost app + window title only.
 * Skips full tree walk — typically <50ms vs 2-15s.
 * Returns JSON: { "app": "...", "window": "...", "elements": [], "timestamp_ms": ... }
 */
export declare function getQuickContext(): string

/** Get run history, most recent first. Returns JSON string. */
export declare function getRunHistory(dbPath: string, limit: number): string

/** Get step results for a specific run. Returns JSON string. */
export declare function getStepResults(dbPath: string, runId: number): string

/** Get working memory for a workflow. Returns JSON string. */
export declare function getWorkingMemory(dbPath: string, workflowName: string): string

export declare function initTracing(): void

/** Check if the Cortex is currently running. */
export declare function isCortexRunning(): boolean

/** Press a key combination (e.g., ["Ctrl", "C"]). */
export declare function keyCombo(keys: Array<string>): void

/** Press a key down without releasing. Pair with key_up() for independent modifier control. */
export declare function keyDown(key: string): void

/** Press a single key (e.g., "Enter", "Tab", "Escape"). */
export declare function keyPress(key: string): void

/** Release a key that was previously pressed with key_down(). */
export declare function keyUp(key: string): void

/**
 * List windows from the capture backend. Returns JSON string.
 *
 * This exposes the same platform capture IDs that `capture_window` expects.
 */
export declare function listCaptureWindows(): string

/** List available monitors. Returns JSON string. */
export declare function listMonitors(): string

/**
 * List all visible windows on screen. Returns JSON string.
 * Uses cel-signals (CGWindowListCopyWindowInfo on macOS) as the canonical source.
 */
export declare function listWindows(): string

/**
 * Send a text-only LLM chat completion. Returns the model response string.
 *
 * If `provider` is omitted, reads config from env vars (CEL_LLM_PROVIDER, etc.).
 */
export declare function llmComplete(systemPrompt: string, userPrompt: string, provider?: string | undefined | null, apiKey?: string | undefined | null, model?: string | undefined | null, endpoint?: string | undefined | null, maxTokens?: number | undefined | null): Promise<string>

/**
 * Send an LLM chat completion with an attached image. Returns the model response string.
 *
 * If `provider` is omitted, reads config from env vars.
 * Uses the Vision role for provider resolution.
 */
export declare function llmCompleteWithImage(systemPrompt: string, imageBase64: string, userPrompt: string, provider?: string | undefined | null, apiKey?: string | undefined | null, model?: string | undefined | null, endpoint?: string | undefined | null, maxTokens?: number | undefined | null): Promise<string>

/**
 * Send a multi-turn LLM chat completion. Takes a JSON array of messages,
 * each with "role" and "content" fields. Uses the Planner role for provider resolution.
 */
export declare function llmCompleteWithMessages(messagesJson: string, maxTokens?: number | undefined | null): Promise<string>

/**
 * Send a text-only LLM chat completion using a specific role for provider resolution.
 *
 * The role determines which env vars are used (e.g., CEL_LLM_VALIDATOR_PROVIDER).
 * Valid roles: "planner", "observer", "vision", "general", "validator", "localizer", "orchestrator".
 */
export declare function llmCompleteWithRole(systemPrompt: string, userPrompt: string, role: string, maxTokens?: number | undefined | null): Promise<string>

/** Log a step result during a workflow run. Returns the step row ID. */
export declare function logStep(dbPath: string, runId: number, stepIndex: number, stepId: string, action: string, success: boolean, confidence: number, contextSnapshot?: string | undefined | null, error?: string | undefined | null): number

/**
 * Create a resilient ContextReference from a ContextElement JSON.
 * Returns JSON string of ContextReference.
 */
export declare function makeReference(elementJson: string, screenWidth: number, screenHeight: number): string

/** Move the mouse to absolute screen coordinates. */
export declare function mouseMove(x: number, y: number): void

/**
 * Move the mouse smoothly with human-like interpolation (ease-in-out cubic).
 * `duration_ms`: movement duration in milliseconds (0 = instant).
 */
export declare function mouseMoveSmooth(x: number, y: number, durationMs: number): void

/** Get the current mouse cursor position as [x, y]. */
export declare function mousePosition(): Array<number>

/** Notify the Cortex that an action was taken. Resets idle tracking. */
export declare function notifyCortexAction(action: string): void

/** Paste from clipboard (Cmd+V on macOS, Ctrl+V on others). */
export declare function paste(): void

/**
 * Plan a single step given a goal, current context, and step history.
 * Returns a JSON PlannedStep: { reasoning, action, expected_outcome, confidence }.
 *
 * The caller runs the loop in TypeScript, calling this function per iteration
 * with fresh context and accumulated history.
 */
export declare function planStep(goal: string, contextJson: string, historyJson: string, provider?: string | undefined | null, apiKey?: string | undefined | null, model?: string | undefined | null, endpoint?: string | undefined | null, maxTokens?: number | undefined | null, maxSteps?: number | undefined | null, loopWarning?: string | undefined | null, deviceBaselineJson?: string | undefined | null): Promise<string>

/**
 * Plan a step WITHOUT screen context (blind mode).
 * Uses device baseline (OS, shortcuts, installed apps) instead of element table.
 * Much faster — no accessibility tree walk needed.
 */
export declare function planStepBlind(goal: string, historyJson: string, deviceBaselineJson: string, maxSteps?: number | undefined | null, loopWarning?: string | undefined | null): Promise<string>

/**
 * Poll for watchdog events by comparing current context against the last snapshot.
 * Also drains AXObserver push events and merges them into the output.
 * Returns JSON array of CelEvents.
 */
export declare function pollEvents(): string

/** Check if a registered adapter's target app is running. */
export declare function probeAdapter(name: string): Promise<boolean>

/** Query knowledge facts by keyword. Returns JSON string. */
export declare function queryKnowledge(dbPath: string, query: string): string

/** Read the current mental model as JSON. Instant — reads shared memory. */
export declare function readCortexModel(): string

/** Register a Rust-native adapter by name. */
export declare function registerAdapter(name: string): Promise<void>

/** Report a consecutive action failure to the Cortex. */
export declare function reportCortexActionFailure(): void

/** Report a successful action to the Cortex. */
export declare function reportCortexActionSuccess(): void

/**
 * Resolve a ContextReference against a ScreenContext snapshot.
 * Returns JSON ContextElement, or "null" if no match.
 */
export declare function resolveReference(contextJson: string, referenceJson: string): string

/** Right-click at absolute screen coordinates. */
export declare function rightClick(x: number, y: number): void

/** Run TTL eviction policies. Returns JSON with deleted row counts. */
export declare function runEviction(dbPath: string, runRetentionDays: number, knowledgeRetentionDays: number): string

/**
 * Run a goal through the canonical agent loop.
 *
 * When the runtime backend is `Local` (default), executes in-process via
 * the booted Cortex + CanonicalGoalRunner. When `Remote`, submits to the
 * configured worker and polls until completion. Only `goal`, `max_steps`,
 * and `timeout_ms` are honored on the JS side; legacy flags
 * (`enable_vision`, `enable_decomposition`, `self_heal`, `enable_notebook`)
 * are silently ignored — the canonical agent does not expose them.
 */
export declare function runGoalRust(configJson: string): Promise<string>

/** Scroll at the current position. */
export declare function scroll(dx: number, dy: number): void

/** Full-text search over knowledge using FTS5. Returns JSON string. */
export declare function searchKnowledge(dbPath: string, query: string, workflowScope: string | undefined | null, limit: number): string

/** Select all text in the focused element (Cmd+A on macOS, Ctrl+A on others). */
export declare function selectAll(): void

/**
 * Execute a shell command and return its stdout.
 * Restricted to safe commands: open, osascript, defaults, system_profiler.
 * Returns JSON: { "success": bool, "stdout": string, "stderr": string, "code": number }
 */
export declare function shellExec(command: string, args: Array<string>): string

/** Start a workflow run. Returns the run ID. */
export declare function startRun(dbPath: string, workflowName: string, stepsTotal: number): number

/**
 * Initialize the context watchdog for change detection.
 * Also starts the AXObserver for push-based accessibility notifications.
 */
export declare function startWatchdog(): void

/** Stop the Cortex — stops the background perception loop. */
export declare function stopCortex(): void

/** Stop and reset the watchdog. Also stops the AXObserver. */
export declare function stopWatchdog(): void

/** Triple-click at absolute screen coordinates (selects full line/paragraph). */
export declare function tripleClick(x: number, y: number): void

/** Type a string of text. */
export declare function typeText(text: string): void

/** Update working memory for a workflow. */
export declare function updateWorkingMemory(dbPath: string, workflowName: string, content: string): void
