//! `#[ipc_dispatch]` — derive the JSON-RPC dispatch fn from the `Handler` trait.
//!
//! The IPC surface used to be wired in two hand-maintained places: the trait
//! method (in `handler.rs`) and a `match` arm in `server.rs`. They could drift
//! — a handler method with no matching arm was silently unreachable
//! (`MethodNotFound`), which is exactly how `events.publish` shipped broken.
//!
//! Applying `#[ipc_dispatch]` to the trait makes that impossible: every method
//! annotated with `#[method("wire.name")]` is BOTH a trait method and a
//! generated dispatch arm — one source of truth. A method without a route
//! cannot exist, because the route is derived from the method.
//!
//! The call shape is inferred from the signature (no hand-maintained variant
//! list):
//! - no args (besides `&self`)            → `handler.m().await`
//! - one `FrameSink` arg                  → `handler.m(sink).await`
//! - one non-sink arg                     → `handler.m(parse(params)?).await`
//! - a params arg + a `FrameSink` arg     → `handler.m(parse(params)?, sink).await`
//!
//! Methods with no `#[method(...)]` attribute (lifecycle hooks like
//! `on_connect`) are left untouched and not dispatched.

use proc_macro::TokenStream;
use quote::quote;
use syn::{FnArg, ItemTrait, LitStr, TraitItem, Type};

/// Attribute macro placed on the `Handler` trait. Must sit ABOVE
/// `#[async_trait]` so it sees the original `async fn` signatures (it re-emits
/// the trait with `#[async_trait]` intact for the next expansion).
#[proc_macro_attribute]
pub fn ipc_dispatch(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let mut tr = syn::parse_macro_input!(item as ItemTrait);
    let trait_name = tr.ident.clone();
    let mut arms = Vec::new();
    let mut errors = Vec::new();

    for trait_item in &mut tr.items {
        let TraitItem::Fn(method) = trait_item else {
            continue;
        };

        // Pull the wire name out of `#[method("...")]` and strip the helper
        // attribute so the re-emitted trait is clean.
        let mut wire: Option<LitStr> = None;
        method.attrs.retain(|attr| {
            if attr.path().is_ident("method") {
                match attr.parse_args::<LitStr>() {
                    Ok(lit) => wire = Some(lit),
                    Err(e) => errors.push(e.to_compile_error()),
                }
                false
            } else {
                true
            }
        });
        let Some(wire) = wire else {
            continue; // not a dispatched method (e.g. on_connect/on_disconnect)
        };

        let fn_name = method.sig.ident.clone();
        // Typed args, in order (skips the &self receiver).
        let typed: Vec<&syn::PatType> = method
            .sig
            .inputs
            .iter()
            .filter_map(|a| match a {
                FnArg::Typed(pt) => Some(pt),
                FnArg::Receiver(_) => None,
            })
            .collect();

        let call = match typed.as_slice() {
            // no_params: handler.m().await
            [] => quote! { let __r = handler.#fn_name().await?; },
            // sink_only: handler.m(sink).await
            [only] if is_frame_sink(&only.ty) => {
                quote! { let __r = handler.#fn_name(sink).await?; }
            }
            // plain: handler.m(parse(params)?).await
            [_p] => quote! {
                let __p = __parse(params)?;
                let __r = handler.#fn_name(__p).await?;
            },
            // with_sink: handler.m(parse(params)?, sink).await
            [_p, s] if is_frame_sink(&s.ty) => quote! {
                let __p = __parse(params)?;
                let __r = handler.#fn_name(__p, sink).await?;
            },
            _ => {
                errors.push(
                    syn::Error::new_spanned(
                        &method.sig,
                        "#[ipc_dispatch]: unsupported method shape — expected \
                         (), (params), (FrameSink), or (params, FrameSink)",
                    )
                    .to_compile_error(),
                );
                continue;
            }
        };

        arms.push(quote! {
            #wire => {
                #call
                ::serde_json::to_value(&__r).map_err(__ser_err)
            }
        });
    }

    let expanded = quote! {
        #tr

        /// Generated by `#[ipc_dispatch]`. Routes a method string to the
        /// corresponding `Handler` trait method, deserialising params and
        /// serialising the result. Adding/removing a `#[method(...)]` method
        /// adds/removes its arm here automatically — they cannot drift.
        pub async fn dispatch<H: #trait_name + ?Sized>(
            handler: &::std::sync::Arc<H>,
            method: &str,
            params: ::serde_json::Value,
            sink: FrameSink,
        ) -> crate::error::IpcResult<::serde_json::Value> {
            fn __parse<T: ::serde::de::DeserializeOwned>(
                v: ::serde_json::Value,
            ) -> crate::error::IpcResult<T> {
                ::serde_json::from_value(v)
                    .map_err(|e| crate::error::IpcError::InvalidParams(e.to_string()))
            }
            fn __ser_err(e: ::serde_json::Error) -> crate::error::IpcError {
                crate::error::IpcError::Internal(::std::format!("serialize result: {e}"))
            }
            let _ = &sink; // some arms don't use it; silence unused on those builds
            match method {
                #(#arms)*
                other => Err(crate::error::IpcError::MethodNotFound(other.to_string())),
            }
        }

        #(#errors)*
    };

    expanded.into()
}

/// True when `ty`'s final path segment is `FrameSink` (handles `FrameSink`,
/// `crate::handler::FrameSink`, `super::FrameSink`, …).
fn is_frame_sink(ty: &Type) -> bool {
    matches!(ty, Type::Path(tp) if tp.path.segments.last().is_some_and(|s| s.ident == "FrameSink"))
}
