//! Action types — what the gateway intercepts and what it returns.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A proposed action handed to the gateway by a caller (embedded agent,
/// MCP server, or CLI). The gateway constructs a synthetic
/// `agent_action_attempted` event from this and runs the matcher.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ProposedAction {
    /// Normalised caller — `"embedded"`, `"mcp:cursor"`, `"mcp:codex"`,
    /// `"cli"`, etc. Becomes `data.caller` in the synthetic event.
    pub caller: String,
    /// The `cel_act` action type — `"fs.copy"`, `"fs.move"`, `"shell.run"`,
    /// `"ax.click"`, etc. Becomes `data.action_type`.
    pub action_type: String,
    /// The action arguments. Becomes `data.action_args`.
    pub action_args: Value,
    /// Optional agent-session ID linking this attempt back to a chat session.
    /// Becomes `data.agent_session_id` when set.
    pub agent_session_id: Option<String>,
    /// Optional working directory / project root for scope-aware rules.
    /// Becomes `data.project_root` when set.
    pub project_root: Option<String>,
}

/// The result of an intercepted action.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ActionOutcome {
    /// The action executed. Carries whatever the actuator returned.
    Executed {
        /// Actuator-specific result payload.
        result: Value,
    },
    /// A `veto` or `soft_block` rule matched. The action did not execute.
    Vetoed {
        /// ID of the matched rule that caused the veto.
        rule_id: String,
        /// Rule name (for display).
        rule_name: String,
        /// Whether this was a `soft_block` (countermeasure suggested) or
        /// a hard `veto`.
        soft_block: bool,
    },
    /// A `require_confirmation` rule matched and the user denied.
    ConfirmationDenied {
        /// ID of the matched rule that requested confirmation.
        rule_id: String,
        /// Rule name (for display).
        rule_name: String,
    },
    /// A `require_confirmation` rule matched and the confirmation timed out.
    ConfirmationTimedOut {
        /// ID of the matched rule that requested confirmation.
        rule_id: String,
        /// Rule name (for display).
        rule_name: String,
        /// Timeout that elapsed, in seconds.
        timeout_s: u64,
    },
}

impl ActionOutcome {
    /// True iff the action actually executed.
    pub fn executed(&self) -> bool {
        matches!(self, ActionOutcome::Executed { .. })
    }
}

/// Sent to the [`crate::ConfirmationBroker`] when a `require_confirmation`
/// rule matches.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ConfirmationRequest {
    /// Stable ID for this confirmation. Generated by the gateway. The broker
    /// surfaces it so the user-facing layer (Tauri modal) can address it.
    pub id: String,
    /// When the confirmation request was raised.
    pub created_at: DateTime<Utc>,
    /// Time after which the gateway treats this as a deny.
    pub expires_at: DateTime<Utc>,
    /// The rule that requested confirmation.
    pub rule_id: String,
    /// Rule name for display.
    pub rule_name: String,
    /// Rule's NL original — what the user wrote when authoring it.
    pub rule_nl_original: String,
    /// The originating proposed action.
    pub action: ProposedAction,
}

/// Response from the [`crate::ConfirmationBroker`].
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ConfirmationDecision {
    /// User approves; action proceeds.
    Allow,
    /// User refuses; action returns [`ActionOutcome::ConfirmationDenied`].
    Deny,
    /// Confirmation expired before the user responded.
    TimedOut,
}
